// Centralized mapping of roles to their default permissions
// This file should be kept in sync with database-seed.js and backend registration logic
import { USER, NOTIFICATION, DOCTOR, APPOINTMENT, MEDICAL_DOSSIER } from './permissions';

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  patient: [
    USER.VIEW_OWN,
    USER.UPDATE_OWN,
    APPOINTMENT.CREATE,
    APPOINTMENT.VIEW_OWN,
    APPOINTMENT.UPDATE_OWN,
    APPOINTMENT.UPDATE_STATUS,
    NOTIFICATION.VIEW_OWN,
    NOTIFICATION.UPDATE_OWN,
  ],
  doctor: [
    USER.VIEW_OWN,
    USER.UPDATE_OWN,
    DOCTOR.VIEW_OWN,
    DOCTOR.UPDATE_OWN,
    DOCTOR.VIEW_AVAILABILITY,
    DOCTOR.MANAGE_AVAILABILITY,
    DOCTOR.VIEW_ABSENCES,
    DOCTOR.MANAGE_ABSENCES,
    APPOINTMENT.CREATE,
    APPOINTMENT.VIEW_OWN,
    APPOINTMENT.UPDATE_ALL,
    APPOINTMENT.UPDATE_STATUS,
    APPOINTMENT.UPDATE_OWN,
    NOTIFICATION.VIEW_OWN,
    NOTIFICATION.UPDATE_OWN,
    MEDICAL_DOSSIER.VIEW_ALL,
    MEDICAL_DOSSIER.MANAGE,
  ],
  responsable: [
    USER.VIEW_OWN,
    USER.UPDATE_OWN,
    DOCTOR.VIEW_ALL,
    DOCTOR.MANAGE,
    DOCTOR.VIEW_AVAILABILITY,
    DOCTOR.MANAGE_AVAILABILITY,
    DOCTOR.VIEW_ABSENCES,
    DOCTOR.MANAGE_ABSENCES,
    APPOINTMENT.CREATE,
    APPOINTMENT.VIEW_ALL,
    APPOINTMENT.UPDATE_ALL,
    APPOINTMENT.UPDATE_OWN,
    APPOINTMENT.UPDATE_STATUS,
    APPOINTMENT.VIEW_OWN,
    NOTIFICATION.VIEW_OWN,
    NOTIFICATION.UPDATE_OWN,
  ],
  admin: [], // special case: handled as all permissions
};
